on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
          check-latest: true
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci && npm run build
        working-directory: web-client
      - run: go build -o bin/music-server .
      - uses: actions/upload-artifact@v2
        with:
          name: build-outputs
          path: |
            bin/music-server
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.md
          files: bin/music-server
